AWSTemplateFormatVersion: '2010-09-09'
Description: Create EC2 Instance 

Resources:
  # Create the Security Group
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: '0.0.0.0/0'  # Allow SSH from anywhere
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: '0.0.0.0/0'  # Allow SSH from anywhere

  # Create the EC2 Instance
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro  # Choose instance size, t2.micro is eligible for free tier
      ImageId: ami-07b0c09aab6e66ee9  # Replace with the latest AMI ID for your region
      SecurityGroups:
        - Ref: MySecurityGroup
      KeyName: oregon-wfh  # Replace with your existing EC2 Key Pair for SSH access
      Tags:
        - Key: Name
          Value: MyEC2Instance

